```{r}
install_or_load_pack <- function(pack){
   create.pkg <- pack[!(pack %in% installed.packages()[, "Package"])]
    if (length(create.pkg))
     install.packages(create.pkg, dependencies = TRUE)
     sapply(pack, require, character.only = TRUE)
}
packages <- c("ggplot2",  "data.table", "wordcloud", "tm", "wordcloud2", "tidytext", "devtools", "dplyr", 'tidyverse', 'readxl', 'udpipe', 'rlang', 'plyr', 'lsa', 'rJava', 'openxlsx')
install_or_load_pack(packages)
```

```{r}
#library('writexl')
#library('xlsx')

#library('janeaustenr')
#library('rlang')
```

```{r}
# input_data_Astrahan <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Астраханская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Bashkortastan <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Башкортостан_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Kirovskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Кировская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_MariEl <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Марий Эл_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Mordovia <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Мордовия_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Nijegorodskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Нижегородская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Nijegorodskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Нижегородская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Orenburgskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Оренбургская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Penzenskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Пензенская область_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Permskiy <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Пермский край_посты_2023.xlsx", sheetIndex=1, header = FALSE)
# input_data_Samarskaya <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK 2024/Пермский край_посты_2023.xlsx", sheetIndex=1, header = FALSE)

```

```{r}
# dir_path <- "/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Все данные/Данные из сообществ VK, собранные в 2024/ПФО/14 регионов, 2023 год"
# dir_path <- "/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Все данные/Малые_тестовые_данные"
dir_path <- "/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Все данные/Данные из сообществ VK, собранные в 2024/ПФО/14 регионов, 2023 год"
file_names <- list.files(dir_path, full.names = FALSE)
print(file_names)
file_paths <- list.files(dir_path, full.names = TRUE)
print(file_paths)
```


```{r}

# all_input_data <- list()
# for (i in seq_along(file_paths)) {
#     all_input_data[[i]] <- read.xlsx(file = file_paths[i], sheetIndex = 1, header = FALSE)
# }

```

```{r}
all_input_data <- list()
for (i in seq_along(file_paths)) {
    all_input_data[[i]] <- as.data.frame(read_excel(file_paths[i], col_names = FALSE))
}
```


```{r}
names(all_input_data) <- gsub(".xlsx", '', file_names)
names(all_input_data)
```

```{r}
# test_data_aaa <- list()
# test_data_aaa[[2]] <- read_excel(file_paths[2], col_names = FALSE)
# test_data_aaa
```




```{r}
#input_data1 <- input_data1 %>% mutate(doc_id = 1)
#input_data2 <- input_data2 %>% mutate(doc_id = 2)
#input_data3 <- input_data3 %>% mutate(doc_id = 3)
#input_data_all <- rbind(input_data1, input_data2, input_data3)
```


```{r}
female_names_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Course_work_3d_course_First/Data/female_names_rus.txt", header=FALSE)
male_names_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Course_work_3d_course_First/Data/male_names_rus.txt", header=FALSE)
male_surnames_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/Курсовая_3й-4й_курс/Course_work_3d_course_First/Data/male_surnames_rus.txt", header=FALSE)
```



```{r}
extra_stop_words <- c('и', 'й', 'г', 'единаяроссия', 'единый', 'время', 'территория', 'димитровграда', 'димитровград', 
                           'чебоксар', 'ядринский', 'житель', 'компания', 'министр', 'дом', 'общественный',
                           'программа', 'мероприятие', 'условие', 'ситуация', 'гражданин', 'группа', 'организация',
                           'система', 'оао', 'ооо', 'пао', 'зао', 'центр', 'руководитель', 'конкурс', 'решить', 'говорить',
                           'состав', 'уровень', 'адрес', 'дело', 'заместитель', 'просто', 'данный', 'сайт', 'позолять',
                           'директор', 'полный', 'час', 'неделя', 'рука', 'ядрин', 'погода', 'выбрать',
                           'средство', 'принять', 'чебоксарский', 'пункт', 'получать', 'второй', 'количество',
                           
                           'найти', 'pgrunews', 'хороший', 'занятие', 'ныжный', 'номер', 'отлично', 'лс',
                           'состояние', 'цена', 'вид', 'руба', 'зеркадать', 'ть', 'торг', 'нужный', 'муниципальный',
                           'округ', 'ип', 'ссылка', 'задний', 'друг', 'замить', 'бесплатный', 
                           'участник', 'слово', 'прогноз', 'удобный', 'тд', 'летний', 'лето',
                           'астраханский', 'астрахань', 'астраханскаяобласть', 'федеральный', 'государственный',
                           'министерство', 'команда', 'асраханец', 'еррб', 'россии', 'ербашкортостан', 'мера',
                           'гтркбашкортостан', 'необходимый', 'возможность', 'предварительный', 'отделение',
                           'объект', 'погодавбашкирия', 'gtrkrb', 'проходить', 'правительство', 'премьерминистр',
                           'правительстворб', 'период', 'пресечить', 'сотрудник', 'гтрквяток', 'еркир', 'мс',
                           'мс', 'ночь', 'мй', 'обещать', 'ожидаться', 'c',
                           
                           'правительствомарийэть', 'йошкарола', 'цур', 'цура', 'врио', 'федерация', 'исполнять',
                           'врио', 'временно', 'заседание', 'эфир', 'цель', 'направить', 'внимание',
                           'встреча', 'зайцин', 'сфера', 'национальный', 'улица', 'провдоить', 
                           'нижегородскийрайон', 'нижнийновгород', 'пространство', 'урка',
                           'нижегородец', 'администрация', 'департамент', 'горький', 'шалабай', 'номинация',
                           'градус', 'ребенок', 'ребёнок', 'ый', 'находится', 'находиться', 'сильный',
                           'перй', 'ул', 'прогнозируть', 'красноярский', 'самар', 'толльятъ', 'тольять',
                           'толльять','тольятть', 'ярин', 'иметься', 'самарь', 'требоваться', 'зп', 'сутка','двое',
                           'магазин', 'саратов', 'сарат', 'составить', 'течение', 'случай', 'общий', 'энгельсский',
                           'саратовец', 'саратовый', 'балашовский', 'начало', 'областной', 'составлять',
                           'учреждение', 'совет', 'комитет', 'казанский', 'средний', 'азнакаевский',
                           'удмуртский', 'ижевска', 'мояудмуртия', 'ува', 'увинский', 'ижевсок', 'ижевск', 'астраханец',
                           'кировчанин',
                           
                           'образовательный', 'этап', 'астраханец', 'проведение', 'спортивный', 'дорожный',
                           'градус', 'федеральный', 'цуринформировать', 'заявка', 'спортсмен', 'победитель', 'всероссийский',
                           'результат', 'учебный', 'современный', 'цурмарийэл', 'зарегистрировать', 'совещание',
                           'деятельность', 'акция', 'проведение', 'мероприятие', 'главный', 'несколько', 'любой',
                           'площадка', 'комиссия', 'зона', 'помощь', 'специалист', 'окружающий', 'профессиональный',
                           'сельский', 'ремний', 'предложение', 'планироваться', 'местный', 'онапомни', 'небольшой',
                           'планироваться', 'председатель', 'совещание', 'обращение', 'республиканский', 'дополнительный',
                           'индивидуальный', 'работник', 'режим', 'решение', 'управление', 'марийский', 'позволять',
                           'деятельность', 'текущий', 'обсудить', 'поблагодарить', 'посетить', 'направление', 'тема',
                           'орган', 'установить', 'участок', 'важноenn', 'пятница', 'свердлово', 'транспортный',
                           'программа', 'ерпенза', 'коронавирусный', 'необходимый', 'возраст', 'возможность',
                           'ситуация', 'средство', 'условие', 'уровень', 'количество', 'неделя', 'участник',
                           'состояние', 'данный', 'позволять', 'адрес', 'охотничий', 'помогать', 'данный',
                           'проводиться', 'здоровый', 'образ', 'активность', 'принять', 'httpspgrunews', 'профессия',
                           'районный', 'действовать', 'заниматься', 'вместе', 'телефон', 'телефона', 'пробегнуть',
                           'отличный', 'хотеть', 'ггра', 'сарансок', 'создание', 'смотреть', 'легкой',
                           'оренбургское', 'профилактический', 'обстоятельство', 'поступить', 'произойти', 'сообщение',
                           'следовать', 'пермь', 'застать', 'желать', 'линия', 'пусть', 'ближайший', 'рядом',
                           'махонин', 'требование', 'внимательный', 'появиться', 'установить', 'режим', 'активный',
                           'несколько', 'категория', 'позволять', 'смен', 'сменный', 'энгельс', 'срок', 'балаковский',
                           'начать', 'план', 'прошлый', 'мр', 'услуга', 'лицо', 'специальный', 'заявка', 'httpskazanfirstrunews',
                           "требовать", "править", "информация", 'обращение', 'править', 'население', 'подготовка', 'ремонт', 
                           'план', 'комплекс', 'маршрут', 'снег', 'гражданин', 'общественный', 'продукт', 'товар', 'дом', 
                           'мероприятие', 'система', 'сохранение', 'проблема', 'труд',  'деньги',  'мир', 'проверка', 
                           'обратиться', 'возбудить', 'факт', 'движение', 
                           'избегать', 'соблюдение', 'явление', 'здание', 'данные', 'правило', 'график', 'источник', 'продукция',
                           'дорога', 'транспорт', 'татарский', 'азнакаево', 'следующий', 'татарстанный', 'парламент', 
                           'httpsvkcomappformidformid', 'выходный', 'ахмадинур', "управлять", "объем", "происшествие",
                           "использование", "обеспечение", "использование", "зауралье", "оперативный", "представитель",
                           "голосоаваний", "секретарь", "рустема", "документ", "считать", "минувший", "столица", "международный",
                           "дождь", "м", "кубок", "фонд", "поздравляе", "мужчина", "женщина", "проводить", "пробный",
                           "узнать", "материал", "статья", "отдел", "денежный", "полицейский", "сторона", "допустить", 
                           "вещество", "соблюдать", "вызов", "мобильный", "знакомый", "родной", "прохождение",
                           "плата", "выплата", "качество", "официальный", "комфортный", "оборудование", "обязанность",
                           "добавить", "предоставление", "размер", "поставить", "касаться", "подготовить", "известный",
                           "госсоветерт", "госсоветерт", "ч", "отношение", "завтра",
                           
                           'ульяновскаяобласть', 'ульяновск', 'ульяновский', 'саранск', 'саранска', 'мордовие', 'рм', 'рма', 'мордовия', 
                           'мордовский', 'заец', 'idюрий', 'главамарийэл', 'марий', 'эл', 'марийэл', 'эть', 'васил', 'чурин', 'кировский', 
                           'кировскаяобласть', 'вятский', 'мельниченко', 'месяц', 'оренбургнуть', 'объясняемрф', 'провести', 'инвестор', 
                           'вести', 'реализация', 'башкортостанный', 'радий', 'подписать', 'проект', 'пермский', 'пермскийкрай', 'край', 
                           'прикамья', 'краевой', 'задача', 'важно', 'оренбуржец', 'оренбург', 'новость', 'подчеркнуть', 'оренбуржье', 
                           'оренбургский', 'оренбургскаяобласть', 'поддержка', 'часть', 'км', 'валерийрадаеть', 'олегнуть', 'должен', 
                           'около', 'рассказать', 'глава', 'губернатор', 'развитие', 'январь', 'февраль', 'март', 'апрель', 'май', 
                           'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь', 'город', 'ecom', 'казань', 'подробность', 
                           'подробный', 'радия', 'процент', 'уф', 'часть', 'вопрос', 'делать', 'сделать', 'благодаря', 'участие', 'пройти', 
                           'идти', 'создать', 'создавать', 'дать',  'рамка', 'место', 'первый', 'получить', 'удмуртия', 'радай', 'юлие', 
                           'пензенский', 'пенза', 'пензенскаяобласть', 'новый', 'лучший', 'самый', 'работа', 'рабочий', 'работать', 
                           'региональный', 'нижегородскаяобладать', 'clubнижегородский', 'нижегородскаяобласть', 'нижегородский', 
                           'нижний', 'новгород', 'чувашия', 'чувашие', 'обть', "бaшҡортостать", "бaшҡортостан", 'командахабиров', 'рб', 
                           'миллиард', 'башкирия', 'башкортостан', 'башкортостана', 'мый', 'аный', 'мухаметшина', 'мухаметшин', 'реть', 
                           'рф', 'день', 'отметить', 'число', 'миллион', 'ход', 'президент','страна', 'тысяча', 'рубль', 'доллар', 'район', 
                           'итог', 'татарстан', 'татарстать', 'российский', 'ма', 'область', 'республика', 'саратовский', 'татарстан', 'татарстана', 'самарский','экономический', 'экономика', 'регион', 'год', "миннихан", "рт", "россия", "рустам", "руст", 'россия', 'конкурентоспособность', 'инновация', 'инвестиция', 'инвестиционный', 'рустамминнихан', 'дмитрий', 'азаров', 'саратовскаяобласть', 'саратовская', 'самарскаяобласть', 'азар', 'стать', 'rn«', 'твой', 'сих', 'ком', 'свой',
                           'слишком', 'нами', 'всему', 'будь', 'саму', 'чаще', 'ваше', 'наш', 'затем', 'еще', 'наши', 'ту', 'каждый',
                           'мочь', 'весь', 'этим', 'наша', 'своих', 'оба', 'который', 'зато', 'те', 'вся', 'ваш', 'такая', 'теми', 'ею', 'нередко',
                           'также', 'чему', 'собой', 'нем', 'вами', 'ими', 'откуда', 'такие', 'тому', 'та', 'очень', 'нему',  'д',
                           'алло', 'оно', 'кому', 'тобой', 'таки', 'мой', 'нею', 'ваши', 'ваша', 'кем', 'мои',
                           'однако', 'сразу', 'свое', 'ними', 'всё', 'неё', 'тех', 'хотя', 'всем', 'тобою', 'тебе', 'одной', 'другие',
                           'буду', 'моё', 'своей', 'такое', 'всею', 'будут', 'своего', 'кого', 'свои', 'мог', 'нам', 'особенно', 'её',
                           'наше', 'кроме', 'вообще', 'вон', 'мною', 'никто', 'это', 'изза', 'именно', 'поэтому', 'будьт', 'являться', 
                           'чувашский', 'тыса', 'смочь', 'ваший', 'гльба', 'ать', 'уть', 'ивать', 'ольги', 'пенз', 'ер', 'иметь', 'олегнуть', 
                           'сг', 'например', 'сообщить', 'сообщать', 'среди', 'нть', 'пер', 'зспермь', 'края', 'ради', 'назвать', 'важный',
                           'ик', 'ульяновсок', 'ульяновска', 'russia', 'reg', 'видео', 'russianpolice', 'mvd', 'police', 'ульяновскаяобласть', 'ульяновскаобласть',
                           'русский', 'личный'
                           )
```

```{r}
clean_corpus <- function(corpus_to_use){
corpus_to_use %>%
   tm_map(removePunctuation) %>%
   tm_map(stripWhitespace) %>%
   tm_map(content_transformer(function(x) iconv(x, to='UTF-8'))) %>%
   tm_map(removeNumbers) %>%
   tm_map(content_transformer(tolower)) 
}
```
```{r}
# corp_city_dfs <- VCorpus(VectorSource(all_input_data))
corp_city_dfs <- list()
for (i in seq_along(all_input_data)) {
    corp_city_dfs[[i]] <- VCorpus(VectorSource(all_input_data[[i]]))
}
names(corp_city_dfs) <- names(all_input_data)
```


```{r}
for (i in seq_along(corp_city_dfs)) {
    corp_city_dfs[[i]] <- clean_corpus(corp_city_dfs[[i]])
}
```
```{r}
# View(gsub("[\U{1F600}-\U{1F64F}\U{1F300}-\U{1F5FF}\U{1F680}-\U{1F6FF}\U{1F1E0}-\U{1F1FF}\U{2500}-\U{2BEF}\U{2702}-\U{27B0}\U{24C2}-\U{1F251}\U{1f926}-\U{1f937}\U{10000}-\U{10ffff}\u{2640}-\u{2642}\u{2600}-\u{2B55}\u{200d}\u{23cf}\u{23e9}\u{231a}\u{fe0f}\u{3030}]", "", corp_city_dfs[[1]][[1]][["content"]], perl = TRUE))
```


```{r}
for (i in seq_along(corp_city_dfs)) {
    corp_city_dfs[[i]][[1]][["content"]] <- gsub("[\U{1F600}-\U{1F64F}\U{1F300}-\U{1F5FF}\U{1F680}-\U{1F6FF}\U{1F1E0}-\U{1F1FF}\U{2500}-\U{2BEF}\U{2702}-\U{27B0}\U{24C2}-\U{1F251}\U{1f926}-\U{1f937}\U{10000}-\U{10ffff}\u{2640}-\u{2642}\u{2600}-\u{2B55}\u{200d}\u{23cf}\u{23e9}\u{231a}\u{fe0f}\u{3030}\U{00B0}\U{20BD}]", "", corp_city_dfs[[i]][[1]][["content"]], perl = TRUE)
}
```


```{r}
library(udpipe)
```

```{r}
gsd_model_raw <- udpipe_download_model(language = "russian-gsd")
```

```{r}
gsd_model <- udpipe_load_model(file = gsd_model_raw$file_model)
```
```{r}
# View(as.data.frame(udpipe_annotate(gsd_model, x = corp_city_dfs[[1]][[1]][["content"]],  parser = "none")))
```

```{r}
annotated_city_dfs <- list()
# annotated_city_dfs[[1]] <- as.data.frame(udpipe_annotate(gsd_model, x = corp_city_dfs[[1]][[1]][["content"]],  parser = "none"))
for (i in seq_along(corp_city_dfs)) {
    annotated_city_dfs[[i]] <- as.data.frame(udpipe_annotate(gsd_model, x = corp_city_dfs[[i]][[1]][["content"]],  parser = "none"))
}
names(annotated_city_dfs) <- names(corp_city_dfs)
```


среднее соличество слов в предложении до удаления стоп-слов

```{r}
#nrow(x) / length(unique(x$sentence))
```
```{r}
annotated_city_dfs_changed <- annotated_city_dfs
for (i in seq_along(annotated_city_dfs_changed)) {
    annotated_city_dfs_changed[[i]]$lemma <- noquote(annotated_city_dfs_changed[[i]]$lemma)
    annotated_city_dfs_changed[[i]]$lemma <- str_replace_all(annotated_city_dfs_changed[[i]]$lemma, "[[:punct:]]", "")
}
```
```{r}
lemmas <- list()
for (i in seq_along(annotated_city_dfs_changed)) {
    lemmas[[i]] <- annotated_city_dfs_changed[[i]]$lemma
}
names(lemmas) <- names(annotated_city_dfs_changed)
```

```{r}
stopwords_combined <- paste(c(stopwords("russian"), extra_stop_words, 
                              tolower(male_names_rus$V1), 
                              tolower(male_surnames_rus$V1), 
                              tolower(female_names_rus$V1)), collapse = "|")
```

```{r}
lemmas_without_stopwords <- lemmas
for (i in seq_along(lemmas)) {
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], paste("\\b(", stopwords_combined, ")\\b"), "")
}
names(lemmas_without_stopwords) <- names(lemmas)
```

```{r}
for (i in seq_along(lemmas_without_stopwords)) {
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], '№', '')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], '−', '')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], '—', '')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'правительстворазвитие', 'развитие')
    # lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'правительстворб', 'правительство')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'цифровый', 'цифровой')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'научныймощность', 'научный мощность')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'club', '')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'ветр', 'ветер')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'школьник', 'школа')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'школьный', 'школа')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'молние', 'молния')
    
    # Новые замены для Ульяновской области
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'полицияроссия', 'полиция')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'осуждеть', 'осуждать')
    lemmas_without_stopwords[[i]] <- str_replace_all(lemmas_without_stopwords[[i]], 'умвд', 'мвд')
    lemmas_without_stopwords[[i]] <- lemmas_without_stopwords[[i]][sapply(lemmas_without_stopwords[[i]], nchar) > 0]
    
}
```

```{r}
freq_ratio_dfs <- lemmas_without_stopwords
for (i in seq_along(freq_ratio_dfs)) {
  freq_ratio_dfs[[i]] <- as.data.frame(sort(table(lemmas_without_stopwords[[i]]), decreasing = TRUE))
  colnames(freq_ratio_dfs[[i]]) <- c("word", "freq")
  # freq_ratio_dfs[[i]]$ratio <- freq_ratio_dfs[[i]]$freq / sum(freq_ratio_dfs[[i]]$freq) * 100  !!! CAN BE USEFUL
  freq_ratio_dfs[[i]]$tf <- freq_ratio_dfs[[i]]$freq / nrow(freq_ratio_dfs[[i]]) 
}
names(freq_ratio_dfs) <- names(lemmas_without_stopwords)
```

```{r}
for (i in seq_along(freq_ratio_dfs)) {
  colnames(freq_ratio_dfs[[i]]) <- c("word", 
                                     paste0("freq_", names(freq_ratio_dfs)[[i]], sep = ""),
                                     paste0("tf_", names(freq_ratio_dfs)[[i]], sep = ""))
}
```


```{r}
#TermDocumentMatrix(VectorSource(c(paste(tmp1, sep=' '), paste(tmp2, sep=' '), paste(tmp3, sep=' '))))
#View(as.matrix(TermDocumentMatrix(VectorSource(c(paste(tmp1, sep=' '), paste(tmp2, sep=' '), paste(tmp3, sep=' '))))))
```

среднее количество слов в предложении после удаления стоп-слов

```{r}
# length(tmp) / length(unique(x$sentence))
```



```{r}
# write.xlsx(top_n(d1, 15)[1:15, ], "//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast.xlsx", sheetName = "Sheet3", append=TRUE)
```

```{r}
# write.xlsx(top_n(d2, 15)[1:15, ], "//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast.xlsx", sheetName = "Sheet2", append=TRUE)
```

```{r}
# write.xlsx(top_n(d3, 15)[1:15, ], "//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast.xlsx", sheetName = "Sheet3", append=TRUE)
```



```{r}
# jpeg(width = 1024, height = 768, quality = 10000, pointsize = 28,  file="//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast_2023 Wordcloud.jpeg")
```

```{r}
# jpeg(width = 1024, height = 768, quality = 10000, pointsize = 28,  file="//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast_2023 Wordcloud.jpeg")
#wordcloud(d$word, d$freq, random.order=FALSE, rot.per=0.2, scale=c(3, .5), max.words=190, colors=brewer.pal(8, "Dark2"))
#dev.off()
```

```{r}
# jpeg(width = 1280, height = 720, quality= 100000, pointsize = 28, file="//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты 2023//Nizhegorodskaya_Oblast_2023 Barplot.jpeg")
#barplot(d[1:15,]$freq, las = 2, names.arg = d[1:15,]$word,
#        col ="lightblue", main ="Наиболее частые слова",
#        ylab = "Частота слов", cex.names = 0.55)
```

```{r}
```

```{r}
# lkm <- x %>% filter(x$lemma %in% d$word[1:15]) 
# lkm <- lkm  %>% group_by(lkm$lemma) %>% count(unique(lkm$doc_id))
```

```{r}
#total_words <- x %>% 
#  group_by(lemma) %>% 
 # summarize(sum(nrow(unique(doc_id))))
```

```{r}
#x_tidy <- corp_city_df[["1"]][["content"]] %>%
#  unnest_tokens(word, lemma)

# Применение функции bind_tf_idf
#x_tidy <- x_tidy %>%
#  bind_tf_idf(word, doc_id, n)

# Вывод результата
#head(x_tidy)

```

```{r}
#select(x, lemma, doc_id) %>%  bind_tf_idf(lemma, doc_id)

```

```{r}
#tidy_x <- select(x, doc_id, lemma) %>%  count(doc_id, lemma, sort = TRUE) 
#tf_idf <- tidy_x %>%
#  bind_tf_idf(lemma, doc_id, n) 
#View(tf_idf %>% filter(lemma %in% c(as.character(d$word[1:15]))))

```

```{r}
all_regions_tf_idf_df <- join_all(freq_ratio_dfs, by = 'word', type = 'full', match = "all")
```

```{r}
# all_regions_tf_idf_df <- full_join()
```


```{r}
all_regions_tf_idf_df <- all_regions_tf_idf_df %>% replace(is.na (.), 0)
```
```{r}
all_regions_freq_df <- select(all_regions_tf_idf_df, 'word', c(grep('^freq', names(all_regions_tf_idf_df))))
```
```{r}
all_regions_freq_df <- all_regions_freq_df %>% mutate(num_of_occurrences = rowSums(select(all_regions_freq_df, names(all_regions_freq_df)[names(all_regions_freq_df) != 'word']) != 0))

all_regions_freq_df <- all_regions_freq_df %>% mutate(idf = log(4 / (1 + num_of_occurrences) + 1))
```

```{r}
all_regions_tf_idf_df <- all_regions_tf_idf_df %>% mutate(num_of_occurrences = all_regions_freq_df$num_of_occurrences)

all_regions_tf_idf_df <- all_regions_tf_idf_df %>% mutate(idf = all_regions_freq_df$idf)
```

```{r}
all_regions_tf_idf_without_freq_df <- select(all_regions_tf_idf_df, 'word', c(grep('^tf', names(all_regions_tf_idf_df)), 'idf'))

for (i in seq_along(names(all_input_data))) {
  all_regions_tf_idf_without_freq_df[[paste0("tf_idf_",  names(all_input_data)[[i]], sep = "")]] <- all_regions_tf_idf_without_freq_df[[i + 1]] * all_regions_tf_idf_without_freq_df$idf
}
```

```{r}
tf_idf_only <- select(all_regions_tf_idf_without_freq_df, grep('^tf_idf', names(all_regions_tf_idf_without_freq_df)))
```

```{r}
cos.mat <- cosine(as.matrix(tf_idf_only))
```

```{r}
View(cos.mat)
write.xlsx(cos.mat, 
paste0(dir_path, '/Сравнение с помощью косинусной меры близости.xlsx', sep = ""), sheetName = "Sheet1", append=TRUE, colNames = TRUE, rowNames = TRUE)
```










```{r}

#tdm <- TermDocumentMatrix(as.matrix(tdm_df))
# View(as.matrix(weightTfIdf(tdm)))
```





```{r}
#tdm <- TermDocumentMatrix(VCorpus(DataframeSource(select(x, doc_id, lemma))), control = list(weighting = weightTfIdf))
#m_ <- as.matrix(tdm)
# Преобразуем матрицу в датафрейм
#tfidf_df <- as.data.frame(as.matrix(tdm))
```
