```{r}
install_or_load_pack <- function(pack){
   create.pkg <- pack[!(pack %in% installed.packages()[, "Package"])]
    if (length(create.pkg))
     install.packages(create.pkg, dependencies = TRUE)
     sapply(pack, require, character.only = TRUE)
}
packages <- c("ggplot2",  "data.table", "wordcloud", "tm", "wordcloud2", "tidytext", "devtools", "dplyr", 'tidyverse', 'readxl', 'udpipe', 'writexl', 'xlsx', 'rlang')
install_or_load_pack(packages)
```

```{r}
library('writexl')
library('xlsx')

#library('janeaustenr')
#library('rlang')
```

```{r}
input_data1 <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK/Ulyanovskaya_Oblast_2021.xlsx", sheetIndex=1, header = FALSE
   )
input_data2 <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK/Ulyanovskaya_Oblast_2022.xlsx", sheetIndex=1, header = FALSE
   )
input_data3 <- read.xlsx( "/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Данные из сообществ VK/Ulyanovskaya_Oblast_2023.xlsx", sheetIndex=1, header = FALSE
   )
```
```{r}
#input_data1 <- input_data1 %>% mutate(doc_id = 1)
#input_data2 <- input_data2 %>% mutate(doc_id = 2)
#input_data3 <- input_data3 %>% mutate(doc_id = 3)
#input_data_all <- rbind(input_data1, input_data2, input_data3)
```


```{r}
female_names_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Course_work_3d_course_First/Data/female_names_rus.txt", header=FALSE)
male_names_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Course_work_3d_course_First/Data/male_names_rus.txt", header=FALSE)
male_surnames_rus <- read.csv("/Users/DmitryKonorov/Desktop/Основная_учеба/3й_курс/Курсовая_3й_курс/Course_work_3d_course_First/Data/male_surnames_rus.txt", header=FALSE)
```



```{r}
extra_stop_words <- c('и','димитровграда', 'димитровград', 'ульяновскаяобласть', 'ульяновск', 'ульяновский', 'саранск', 'саранска', 'мордовие', 'рм', 'рма', 'мордовия', 'мордовский', 'заец', 'idюрий', 'главамарийэл', 'марий', 'эл', 'марийэл', 'эть', 'васил', 'чурин', 'кировский', 'кировскаяобласть', 'вятский', 'мельниченко', 'месяц', 'оренбургнуть', 'объясняемрф', 'провести', 'инвестор', 'вести', 'реализация', 'башкортостанный', 'радий', 'подписать', 'проект', 'пермский', 'пермскийкрай', 'край', 'прикамья', 'краевой', 'задача', 'важно', 'оренбуржец', 'оренбург', 'новость', 'подчеркнуть', 'оренбуржье', 'оренбургский', 'оренбургскаяобласть', 'поддержка', 'часть', 'км', 'валерийрадаеть', 'олегнуть', 'должен', 'около', 'рассказать', 'глава', 'губернатор', 'развитие', 'январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь', 'город', 'ecom', 'казань', 'подробность', 'подробный', 'радия', 'процент', 'уф', 'часть', 'вопрос', 'делать', 'сделать', 'благодаря', 'участие', 'пройти', 'идти', 'создать', 'создавать', 'дать',  'рамка', 'место', 'первый', 'получить', 'удмуртия', 'радай', 'юлие', 'пензенский', 'пенза', 'пензенскаяобласть', 'новый', 'лучший', 'самый', 'работа', 'рабочий', 'работать', 'региональный', 'нижегородскаяобладать', 'clubнижегородский', 'нижегородскаяобласть', 'нижегородский', 'нижний', 'новгород', 'чувашия', 'чувашие', 'обть', "бaшҡортостать", "бaшҡортостан", 'командахабиров', 'рб', 'миллиард', 'башкирия', 'башкортостан', 'башкортостана', 'мый', 'аный', 'мухаметшина', 'мухаметшин', 'реть', 'рф', 'день', 'отметить', 'число', 'миллион', 'ход', 'президент','страна', 'тысяча', 'рубль', 'доллар', 'район', 'итог', 'татарстан', 'татарстать', 'российский', 'ма', 'область', 'республика', 'саратовский', 'татарстан', 'татарстана', 'самарский','экономический', 'экономика', 'регион', 'год', "миннихан", "рт", "россия", "рустам", "руст", 'россия', 'конкурентоспособность', 'инновация', 'инвестиция', 'инвестиционный', 'рустамминнихан', 'дмитрий', 'азаров', 'саратовскаяобласть', 'саратовская', 'самарскаяобласть', 'азар', 'стать', 'rn«', 'твой', 'сих', 'ком', 'свой',
'слишком', 'нами', 'всему', 'будь', 'саму', 'чаще', 'ваше', 'наш', 'затем', 'еще', 'наши', 'ту', 'каждый',
'мочь', 'весь', 'этим', 'наша', 'своих', 'оба', 'который', 'зато', 'те', 'вся', 'ваш', 'такая', 'теми', 'ею', 'нередко',
'также', 'чему', 'собой', 'нем', 'вами', 'ими', 'откуда', 'такие', 'тому', 'та', 'очень', 'нему',
'алло', 'оно', 'кому', 'тобой', 'таки', 'мой', 'нею', 'ваши', 'ваша', 'кем', 'мои',
'однако', 'сразу', 'свое', 'ними', 'всё', 'неё', 'тех', 'хотя', 'всем', 'тобою', 'тебе', 'одной', 'другие',
'буду', 'моё', 'своей', 'такое', 'всею', 'будут', 'своего', 'кого', 'свои', 'мог', 'нам', 'особенно', 'её',
'наше', 'кроме', 'вообще', 'вон', 'мною', 'никто', 'это', 'изза', 'именно', 'поэтому', 'будьт', 'являться', 'чувашский', 'тыса', 'смочь', 'ваший', 'гльба', 'ать', 'уть', 'ивать', 'ольги', 'пенз', 'ер', 'иметь', 'олегнуть', 'сг', 'например', 'сообщить', 'сообщать', 'среди', 'нть', 'пер', 'зспермь', 'края', 'ради', 'назвать', 'важный')
```

```{r}
clean_corpus <- function(corpus_to_use){
corpus_to_use %>%
   tm_map(removePunctuation) %>%
   tm_map(stripWhitespace) %>%
   tm_map(content_transformer(function(x) iconv(x, to='UTF-8'))) %>%
   tm_map(removeNumbers) %>%
   tm_map(content_transformer(tolower)) 
}
```

```{r}
corp_city_df1 <- VCorpus(VectorSource(input_data1))
corp_city_df2 <- VCorpus(VectorSource(input_data2))
corp_city_df3 <- VCorpus(VectorSource(input_data3))
```
```{r}
corp_city_df1 <-  clean_corpus(corp_city_df1)
corp_city_df2 <-  clean_corpus(corp_city_df2)
corp_city_df3 <-  clean_corpus(corp_city_df3)
```

```{r}
corp_city_df1[["1"]][["content"]] <- gsub("[\U{1F600}-\U{1F64F}\U{1F300}-\U{1F5FF}\U{1F680}-\U{1F6FF}\U{1F1E0}-\U{1F1FF}\U{2500}-\U{2BEF}\U{2702}-\U{27B0}\U{24C2}-\U{1F251}\U{1f926}-\U{1f937}\U{10000}-\U{10ffff}\u{2640}-\u{2642}\u{2600}-\u{2B55}\u{200d}\u{23cf}\u{23e9}\u{231a}\u{fe0f}\u{3030}]", "", corp_city_df1[["1"]][["content"]], perl = TRUE)
corp_city_df2[["1"]][["content"]] <- gsub("[\U{1F600}-\U{1F64F}\U{1F300}-\U{1F5FF}\U{1F680}-\U{1F6FF}\U{1F1E0}-\U{1F1FF}\U{2500}-\U{2BEF}\U{2702}-\U{27B0}\U{24C2}-\U{1F251}\U{1f926}-\U{1f937}\U{10000}-\U{10ffff}\u{2640}-\u{2642}\u{2600}-\u{2B55}\u{200d}\u{23cf}\u{23e9}\u{231a}\u{fe0f}\u{3030}]", "", corp_city_df2[["1"]][["content"]], perl = TRUE)
corp_city_df3[["1"]][["content"]] <- gsub("[\U{1F600}-\U{1F64F}\U{1F300}-\U{1F5FF}\U{1F680}-\U{1F6FF}\U{1F1E0}-\U{1F1FF}\U{2500}-\U{2BEF}\U{2702}-\U{27B0}\U{24C2}-\U{1F251}\U{1f926}-\U{1f937}\U{10000}-\U{10ffff}\u{2640}-\u{2642}\u{2600}-\u{2B55}\u{200d}\u{23cf}\u{23e9}\u{231a}\u{fe0f}\u{3030}]", "", corp_city_df3[["1"]][["content"]], perl = TRUE)
```

```{r}
library(udpipe)
```

```{r}
gsd_model_raw <- udpipe_download_model(language = "russian-gsd")
```

```{r}
gsd_model <- udpipe_load_model(file = gsd_model_raw$file_model)
```

```{r}
x1 <- udpipe_annotate(gsd_model, x = corp_city_df1[["1"]][["content"]],  parser = "none")
x1 <- as.data.frame(x1)

x2 <- udpipe_annotate(gsd_model, x = corp_city_df2[["1"]][["content"]],  parser = "none")
x2 <- as.data.frame(x2)

x3 <- udpipe_annotate(gsd_model, x = corp_city_df3[["1"]][["content"]],  parser = "none")
x3 <- as.data.frame(x3)
```

среднее соличество слов в предложении до удаления стоп-слов

```{r}
nrow(x) / length(unique(x$sentence))
```

```{r}
# x <- VCorpus(VectorSource(x$lemma))
x1$lemma <- noquote(x1$lemma)
x1$lemma <- str_replace_all(x1$lemma, "[[:punct:]]", "")
tmp1 <- x1$lemma

x2$lemma <- noquote(x2$lemma)
x2$lemma <- str_replace_all(x2$lemma, "[[:punct:]]", "")
tmp2 <- x2$lemma

x3$lemma <- noquote(x3$lemma)
x3$lemma <- str_replace_all(x3$lemma, "[[:punct:]]", "")
tmp3 <- x3$lemma
```

```{r}
stopwords_combined <- paste(c(stopwords("russian"), extra_stop_words, 
                              tolower(male_names_rus$V1), 
                              tolower(male_surnames_rus$V1), 
                              tolower(female_names_rus$V1)), collapse = "|")
tmp1 <- str_replace_all(x1$lemma, paste("\\b(", stopwords_combined, ")\\b"), "")
tmp2 <- str_replace_all(x2$lemma, paste("\\b(", stopwords_combined, ")\\b"), "")
tmp3 <- str_replace_all(x3$lemma, paste("\\b(", stopwords_combined, ")\\b"), "")
#cleaned_lemma <- gsub(paste0("\\b(", stopwords_combined, ")\\b"), "", x$lemma)
```

```{r}
tmp1 <- str_replace_all(tmp1, '№', '')
tmp1 <- str_replace_all(tmp1, '−', '')
tmp1 <- str_replace_all(tmp1, '—', '')

tmp2 <- str_replace_all(tmp2, '№', '')
tmp2 <- str_replace_all(tmp2, '−', '')
tmp2 <- str_replace_all(tmp2, '—', '')

tmp3 <- str_replace_all(tmp3, '№', '')
tmp3 <- str_replace_all(tmp3, '−', '')
tmp3 <- str_replace_all(tmp3, '—', '')
```

```{r}
tmp1 <- str_replace_all(tmp1, 'правительстворазвитие', 'правительство')
tmp1 <- str_replace_all(tmp1, 'правительстворб', 'правительство')
tmp1 <- str_replace_all(tmp1, 'цифровый', 'цифровой')
tmp1 <- str_replace_all(tmp1, 'научныймощность', 'научный мощность')
tmp1 <- str_replace_all(tmp1, 'club', '')
tmp1 <- str_replace_all(tmp1, 'правительствомарийэть', 'правительство')
tmp1 <- str_replace_all(tmp1, 'цура', 'цур')
tmp1 <- tmp1[sapply(tmp1, nchar) > 0]

tmp2 <- str_replace_all(tmp2, 'правительстворазвитие', 'правительство')
tmp2 <- str_replace_all(tmp2, 'правительстворб', 'правительство')
tmp2 <- str_replace_all(tmp2, 'цифровый', 'цифровой')
tmp2 <- str_replace_all(tmp2, 'научныймощность', 'научный мощность')
tmp2 <- str_replace_all(tmp2, 'club', '')
tmp2 <- str_replace_all(tmp2, 'правительствомарийэть', 'правительство')
tmp2 <- str_replace_all(tmp2, 'цура', 'цур')
tmp2 <- tmp2[sapply(tmp2, nchar) > 0]

tmp3 <- str_replace_all(tmp3, 'правительстворазвитие', 'правительство')
tmp3 <- str_replace_all(tmp3, 'правительстворб', 'правительство')
tmp3 <- str_replace_all(tmp3, 'цифровый', 'цифровой')
tmp3 <- str_replace_all(tmp3, 'научныймощность', 'научный мощность')
tmp3 <- str_replace_all(tmp3, 'club', '')
tmp3 <- str_replace_all(tmp3, 'правительствомарийэть', 'правительство')
tmp3 <- str_replace_all(tmp3, 'цура', 'цур')
tmp3 <- tmp3[sapply(tmp3, nchar) > 0]

```
```{r}
TermDocumentMatrix(VectorSource(c(paste(tmp1, sep=' '), paste(tmp2, sep=' '), paste(tmp3, sep=' '))))
View(as.matrix(TermDocumentMatrix(VectorSource(c(paste(tmp1, sep=' '), paste(tmp2, sep=' '), paste(tmp3, sep=' '))))))
```

среднее количество слов в предложении после удаления стоп-слов

```{r}
length(tmp) / length(unique(x$sentence))
```

```{r}
v1 <- sort(table(tmp1), decreasing = TRUE)
d1 <- as.data.frame(v1)
colnames(d1) <- c("word", "freq")
d1$ratio <- d1$freq / sum(d1$freq) * 100
d1$tf <- d1$freq / nrow(d1) 

v2 <- sort(table(tmp2), decreasing = TRUE)
d2 <- as.data.frame(v2)
colnames(d2) <- c("word", "freq")
d2$ratio <- d2$freq / sum(d2$freq) * 100
d2$tf <- d2$freq / nrow(d2) 

v3 <- sort(table(tmp3), decreasing = TRUE)
d3 <- as.data.frame(v3)
colnames(d3) <- c("word", "freq")
d3$ratio <- d3$freq / sum(d3$freq) * 100
d3$tf <- d3$freq / nrow(d3) 
```

```{r}
# top_n(d, 15)[1:15, ]
```

```{r}
write.xlsx(top_n(d, 15)[1:15, ], "//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты//Ulyanovskaya_Oblast.xlsx", sheetName = "Sheet3", append=TRUE)
```

```{r}
jpeg(width = 1024, height = 768, quality = 10000, pointsize = 28,  file="//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты//Ulyanovskaya_Oblast_2023 Wordcloud.jpeg")
wordcloud(d$word, d$freq, random.order=FALSE, rot.per=0.2, scale=c(3, .5), max.words=190, colors=brewer.pal(8, "Dark2"))
dev.off()
```

```{r}
jpeg(width = 1280, height = 720, quality= 100000, pointsize = 28, file="//Users//DmitryKonorov//Desktop//Основная_учеба//3й_курс//Курсовая_3й_курс//Результаты//Ulyanovskaya_Oblast_2023 Barplot.jpeg")
barplot(d[1:15,]$freq, las = 2, names.arg = d[1:15,]$word,
        col ="lightblue", main ="Наиболее частые слова",
        ylab = "Частота слов", cex.names = 0.55)
```

```{r}
```

```{r}
# lkm <- x %>% filter(x$lemma %in% d$word[1:15]) 
# lkm <- lkm  %>% group_by(lkm$lemma) %>% count(unique(lkm$doc_id))
```

```{r}
#total_words <- x %>% 
#  group_by(lemma) %>% 
 # summarize(sum(nrow(unique(doc_id))))
```

```{r}
#x_tidy <- corp_city_df[["1"]][["content"]] %>%
#  unnest_tokens(word, lemma)

# Применение функции bind_tf_idf
#x_tidy <- x_tidy %>%
#  bind_tf_idf(word, doc_id, n)

# Вывод результата
#head(x_tidy)

```

```{r}
#select(x, lemma, doc_id) %>%  bind_tf_idf(lemma, doc_id)

```

```{r}
#tidy_x <- select(x, doc_id, lemma) %>%  count(doc_id, lemma, sort = TRUE) 
#tf_idf <- tidy_x %>%
#  bind_tf_idf(lemma, doc_id, n) 
#View(tf_idf %>% filter(lemma %in% c(as.character(d$word[1:15]))))

```


```{r}
d_all <- full_join(full_join(d1, d2, by='word'), d3, by='word')
d_all <- d_all %>% replace(is.na (.), 0)
tf_idf <- select(d_all, 'word', 'freq.x', 'tf.x', 'freq.y','tf.y', 'freq', 'tf')
names(tf_idf) <- c('word', 'freq1', 'tf1', 'freq2', 'tf2', 'freq3', 'tf3')

tdm_df <- select(d_all, 'word', 'freq.x', 'freq.y', 'freq')
names(tdm_df) <- c('word', 'freq1', 'freq2', 'freq3')
#names(tdm_df) <- c('word', 'freq1', 'ratio1', 'tf1', 'freq2', 'ratio2', 'tf2', 'freq3', 'ratio3', 'tf3')
```
```{r}
tdm_df <- tdm_df %>% mutate(num_of_occurrences = rowSums(select(tdm_df, 'freq1', 'freq2', 'freq3') != 0))
tdm_df <- tdm_df %>% mutate(idf = log(4 / (1 + num_of_occurrences) + 1))
```
```{r}
tf_idf <- tf_idf %>% mutate(num_of_occurrences = tdm_df$num_of_occurrences)
tf_idf <- tf_idf %>% mutate(idf = tdm_df$idf)
```
```{r}
tf_idf <- tf_idf %>% mutate(tf_idf1 = tf1 * idf)
tf_idf <- tf_idf %>% mutate(tf_idf2 = tf2 * idf)
tf_idf <- tf_idf %>% mutate(tf_idf3 = tf3 * idf)
```

```{r}
tf_idf_only <- select(tf_idf, 'tf_idf1', 'tf_idf2', 'tf_idf3')
cos.mat <- cosine(as.matrix(tf_idf_only))
```
```{r}
View(cos.mat)
```


```{r}

#tdm <- TermDocumentMatrix(as.matrix(tdm_df))
# View(as.matrix(weightTfIdf(tdm)))
```





```{r}
#tdm <- TermDocumentMatrix(VCorpus(DataframeSource(select(x, doc_id, lemma))), control = list(weighting = weightTfIdf))
#m_ <- as.matrix(tdm)
# Преобразуем матрицу в датафрейм
#tfidf_df <- as.data.frame(as.matrix(tdm))
```
